### PR TITLE
HashTypeForCoin: fix return type to uint32

### LINKED ISSUE #1041: TWBitcoinScriptHashTypeForCoin return type should be UInt32
There is no such enum case for Bitcoin Cash and Bitcoin Gold, it will crash in Swift and be null in Kotlin

Kotlin:

```kotlin
assertNotNull(BitcoinScript.hashTypeForCoin(CoinType.BITCOINCASH)) //  will fail
```

Swift:
image

### PR DESCRIPTION
**Pull request by catenocrypt**
HashTypeForCoin: fix return type to uint32, invalid enum values did not go through Swift/Kotlin interfaces.

## Description

For BitcoinCash and BitcoinGold, hashtype is two enum values OR'ed together, which itself not a valid enum value.  This works in C/C++, but in Swift/Kotlin it results in invalid/null value.  This is fixed by changing return type to uint32_t.  Fixes #1041 .

## Testing instructions

C++ unit tests, iOS unit tests.

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

File: tests/Bitcoin/TWBitcoinSigningTests.cpp [hunk 1]
```diff
@@ -583,7 +583,7 @@ TEST(BitcoinSigning, SignP2WSH_NegativeMissingScript) {
 }
 
 TEST(BitcoinSigning, SignP2WSH_NegativeMissingKeys) {
-    const auto input = buildInputP2WSH(TWBitcoinSigHashTypeAll, false, true);
+    const auto input = buildInputP2WSH((uint32_t)TWBitcoinSigHashTypeAll, false, true);
```
Comment (vikmeup) [inline tests/Bitcoin/TWBitcoinSigningTests.cpp:586]: is there a way to avoid casting?
