### PR TITLE
[Android] Update sdk and warnings fixes

### LINKED ISSUE #1202: [Android] Update compile sdk version
```
android {
    compileSdkVersion 30
    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 30        ...
}
```

### PR DESCRIPTION
**Pull request by hewigovens**
Fixes #1202

### CODE REVIEW

**Review by madcake — APPROVED** [review]

**Review by vcoolish — APPROVED** [review]

File: android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cardano/TestCardanoAddress.kt [hunk 1]
```diff
@@ -23,8 +23,9 @@ class TestCardanoAddress {
         val key = PrivateKey("b0884d248cb301edd1b34cf626ba6d880bb3ae8fd91b4696446999dc4f0b5744309941d56938e943980d11643c535e046653ca6f498c014b88f2ad9fd6e71effbf36a8fa9f5e11eb7a852c41e185e3969d518e66e6893c81d3fc7227009952d4".toHexByteArray())
         val pubkey = key.publicKeyEd25519Extended
         val address = AnyAddress(pubkey, CoinType.CARDANO)
-        val expected = AnyAddress("addr1snpa4z7ntyfszv7ckquprdw75w4qjqh0qmya9jtkpxxlzxghlqyvv7l0yjamh8fxraw06p3ua8sj2g2gv98v4849s43t9g2999kquuu5egnprk", CoinType.CARDANO)
+        val expected = AnyAddress("addr1s3tl64970vuthz2j0qkz7kd2ya5j3fxuhdnv333vu38e6c37e4dq80ek4raf7hs3adag2tzpuxz7895a2x8xde5f8jqa8lrjyuqfj5k50pm668", CoinType.CARDANO)
```
Comment (catenocrypt) [inline android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cardano/TestCardanoAddress.kt:26]: Why this change in expected result?

**Review by catenocrypt — CHANGES_REQUESTED** [review]

File: android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cardano/TestCardanoAddress.kt (hunk 1 above)
Comment (hewigovens) [reply android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cardano/TestCardanoAddress.kt:26]: this is the wrong test, `address` and `expected` are not used before

Comment (hewigovens) [reply android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cardano/TestCardanoAddress.kt:26]: take a look at swift test

**Review by catenocrypt — APPROVED** [review]
