### PR TITLE
[evmos]: authz tx unit tests

### LINKED ISSUE #2571: [Bug]: Investigate evmos restake authz tx failure
**Describe the bug**

Unable to process restake authz tx

**To Reproduce**

**Expected behavior**

Be able to process authz tx

**Additional context**

Cosmos ecosystem

### PR DESCRIPTION
**Pull request by Milerius**
## Description

fix #2571 child of #2569

## How to test

Run c++ unit tests

## Types of changes

Add a unit test

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by hewigovens — DISMISSED** [review]

**Review by hewigovens — APPROVED** [review]

**Review by catenocrypt — APPROVED** [review]

File: tests/Evmos/SignerTests.cpp [hunk 1]
```diff
@@ -87,4 +88,39 @@ TEST(EvmosSigner, SignTxJsonEthermintKeyType) {
...
+
+    auto output = Signer::sign(input, TWCoinTypeNativeEvmos);
+    auto expected = R"(
+                {
+                    "mode":"BROADCAST_MODE_BLOCK",
+                    "tx_bytes":"CvUBCvIBCh4vY29zbW9zLmF1dGh6LnYxYmV0YTEuTXNnR3JhbnQSzwEKLGV2bW9zMTJtOWdyZ2FzNjB5azBrdWx0MDc2dnhuc3Jxejh4cGp5OXJwZjNlEixldm1vczE4ZnpxNG5hYzI4Z2ZtYTZncWZ2a3B3cmdwbTVjdGFyMno5bXhmMxpxCmcKKi9jb3Ntb3Muc3Rha2luZy52MWJldGExLlN0YWtlQXV0aG9yaXphdGlvbhI5EjUKM2V2bW9zdmFsb3BlcjF1bWs0MDdlZWQ3YWY2YW52dXQ2bGxnMnpldm5mMGRuMGZlcXFueSABEgYI4LD6pgYSfQpZCk8KKC9ldGhlcm1pbnQuY3J5cHRvLnYxLmV0aHNlY3AyNTZrMS5QdWJLZXkSIwohA4B2WHbj6sH/GWE7z/YW5PRnXYFGaGRAov7gZZI2Fv2nEgQKAggBGAMSIAoaCgZhZXZtb3MSEDQ1MjE0NzUwMDAwMDAwMDAQ+4QLGkAm17CZgB7m+CPVlITnrHosklMTL9zrUeGRs8FL8N0GcRami9zdJ+e3xuXOtJmwP7G6QNh85CRYjFj8a8lpmmJM"
+                })";
+    assertJSONEqual(output.serialized(), expected);
+}
 }
```
Comment (miloserdow) [inline tests/Evmos/SignerTests.cpp:126]: (nit) // namespace TW::whatever
