### PR TITLE
Fix XRP max amount

### LINKED ISSUE #594: Update FIO blockchain type
Current it's `eos`, it might be better to use `fio`

### LINKED ISSUE #595: Increase XRP max amount limit
https://github.com/trustwallet/wallet-core/blob/master/src/Ripple/Transaction.cpp#L16, I think we can use int64 max value or total supply

### PR DESCRIPTION
**Pull request by hewigovens**
Fixes #595 and Fixes #594

### CODE REVIEW

File: src/Ripple/Transaction.cpp [hunk 1]
```diff
@@ -13,7 +13,8 @@ using namespace TW;
 using namespace TW::Ripple;
 
 const int NETWORK_PREFIX = 0x53545800;
-const int64_t MAX_ALLOWED_AMOUNT = 100000000000;
+/// Max supply in drops
+const int64_t MAX_ALLOWED_AMOUNT = 100000000000 * 1000000;
```
Comment (vikmeup) [inline src/Ripple/Transaction.cpp]: why do we need `MAX_ALLOWED_AMOUNT` ?

File: coins.json [hunk 2]
```diff
@@ -1052,7 +1052,7 @@
         "name": "FIO",
         "symbol": "FIO",
         "decimals": 9,
-        "blockchain": "EOS",
+        "blockchain": "FIO",
```
Comment (vikmeup) [inline coins.json]: I would prefer to use blockatlas type as `EOS`, because we gonna integrate EOS in the future, and FIO is a fork of EOS

File: src/Ripple/Transaction.cpp (hunk 1 above)
Comment (vikmeup) [reply src/Ripple/Transaction.cpp]: Can we remove this option and let users to pass any number they think is correct

Comment (hewigovens) [reply src/Ripple/Transaction.cpp]: You can't send coins larger than max supply

Comment (vikmeup) [reply src/Ripple/Transaction.cpp]: but this is common to any blockchain, we don't have 21M limit for bitcoin transaction? can we just remove that limit

File: coins.json (hunk 2 above)
Comment (hewigovens) [reply coins.json]: that was my first thought, some work flow in FIO would be different with EOS

Comment (vikmeup) [reply coins.json]: that works 👍

File: src/Ripple/Transaction.cpp (hunk 1 above)
Comment (hewigovens) [reply src/Ripple/Transaction.cpp]: removed
