### PR TITLE
[Ethereum] Support fixed array in ABI

### LINKED ISSUE #2302: Ethereum ABI: Support for fixed-size arrays
Currently only byte array is supported with fixed size (e.g.  `bytes160`).  Some functions use fixes-size arrays, such as `address[4]`.

Example:
```
multiRoute(bytes msgData, address inputToken, uint256 inputAmount, address outputToken, address[4] referrals)
```

image

https://etherscan.io/tx/0xb6658239f3236e466c8915c34d165423ecc39fb36aa15389951f388ebdf05c75

See also: https://github.com/trustwallet/wallet-core/discussions/2299

### PR DESCRIPTION
**Pull request by Milerius**
## Description

fix #2302 

## How to test

run c++ unit tests

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

File: tests/Ethereum/AbiTests.cpp [hunk 1]
```diff
@@ -962,38 +995,35 @@ TEST(EthereumAbi, DecodeParamsMixed) {
...
 TEST(EthereumAbi, EncodeFunctionWithDynamicArgumentsCase1) {
     auto func = Function("sam", std::vector<std::shared_ptr<ParamBase>>{
-        std::make_shared<ParamByteArray>(Data{0x64, 0x61, 0x76, 0x65}),
-        std::make_shared<ParamBool>(true),
-        std::make_shared<ParamArray>(std::vector<std::shared_ptr<ParamBase>>{
-            std::make_shared<ParamUInt256>(1),
-            std::make_shared<ParamUInt256>(2),
-            std::make_shared<ParamUInt256>(3)
-        })
-    });
```
Comment (hewigovens) [inline tests/Ethereum/AbiTests.cpp:987]: These indentations are nicer, can we tweak clang-format?

Comment (Milerius) [reply tests/Ethereum/AbiTests.cpp:987]: Yes I can turn it off for a scope, from the config it maybe a bit complex

**Review by hewigovens — APPROVED** [review]

File: src/Ethereum/ABI/Array.h [hunk 2]
```diff
@@ -46,4 +47,40 @@ class ParamArray: public ParamCollection
...
+
+    //! Public Definitions
+    using Params = std::vector<std::shared_ptr<ParamBase>>;
+
+    //! Public constructor
+    explicit ParamArrayFix(std::size_t n, const Params& params) noexcept(false)
+        : ParamCollection(), _n(n) {
+        if (params.size() != n) {
+            throw std::runtime_error("params need to have the same size as N");
+        }
```
Comment (catenocrypt) [inline src/Ethereum/ABI/Array.h:64]: I think param n is not needed, can be taken from size of params

File: src/Ethereum/ABI/Array.h [hunk 3]
```diff
@@ -46,4 +47,40 @@ class ParamArray: public ParamCollection
...
+    bool decode(const Data& encoded, size_t& offset_inout) final;
+    bool setValueJson(const std::string& value) final;
+
+private:
+    //! Private member functions
+    void addParams(const std::vector<std::shared_ptr<ParamBase>>& params) noexcept(false);
+
+    //! Private member fields
+    size_t _n;
+    ParamSet _params;
```
Comment (catenocrypt) [inline src/Ethereum/ABI/Array.h:83]: this member can be const, i.e., settable only in ctor, and not modifiable

File: src/Ethereum/ABI/Array.h [hunk 4]
```diff
@@ -46,4 +47,40 @@ class ParamArray: public ParamCollection
...
+        : ParamCollection(), _n(n) {
+        if (params.size() != n) {
+            throw std::runtime_error("params need to have the same size as N");
+        }
+        this->addParams(params);
+    }
+
+    //! Public member methods
+    [[nodiscard]] std::size_t getCount() const final { return _n; }
+    [[nodiscard]] size_t getSize() const final { return paddingSize + _params.getSize(); }
```
Comment (catenocrypt) [inline src/Ethereum/ABI/Array.h:70]: Is padding always added? ParamSet.getSize() does not inlcude padding?

**Review by catenocrypt — APPROVED** [review]

File: src/Ethereum/ABI/Array.h (hunk 3 above)
Comment (Milerius) [reply src/Ethereum/ABI/Array.h:83]: I think it's problematic to call Decode, and setValueJson if this member is const

File: src/Ethereum/ABI/Array.h (hunk 4 above)
Comment (Milerius) [reply src/Ethereum/ABI/Array.h:70]: It's seems so, I guess `params.getSize()` should be equal to `hex(encoded).size()` alright?

File: src/Ethereum/ABI/Array.cpp [hunk 5]
```diff
@@ -133,4 +133,44 @@ std::string ParamArray::getExtraTypes(std::vector<std::string>& ignoreList) cons
...
+        _params.getParamUnsafe(idx)->setValueJson(eString);
+        ++idx;
+    }
+    return true;
+}
+
+void ParamArrayFix::addParams(const Params& params) {
+    auto addParamFunctor = [this](auto&& param) {
+        if (param == nullptr) {
+            throw std::runtime_error("param can't be nullptr");
```
Comment (miloserdow) [inline src/Ethereum/ABI/Array.cpp:166]: Exceptions are not working on wasm, maybe use assert(false && "message") so message won't be lost?

File: src/Ethereum/ABI/Array.cpp [hunk 6]
```diff
@@ -133,4 +133,44 @@ std::string ParamArray::getExtraTypes(std::vector<std::string>& ignoreList) cons
...
+bool ParamArrayFix::decode(const Data& encoded, size_t& offset_inout) {
+    std::size_t origOffset = offset_inout;
+    auto res = this->_params.decode(encoded, offset_inout);
+    // padding
+    offset_inout = origOffset + ValueEncoder::paddedTo32(offset_inout - origOffset);
+    return res;
+}
+
+bool ParamArrayFix::setValueJson(const std::string& value) {
+    auto valuesJson = json::parse(value, nullptr, false);
```
Comment (miloserdow) [inline src/Ethereum/ABI/Array.cpp:149]: Could it fail / throw something?

File: src/Ethereum/ABI/Array.cpp (hunk 5 above)
Comment (Milerius) [reply src/Ethereum/ABI/Array.cpp:166]: Assertion break the coverage unit tests, I'm not against it but we will end up having preprocessor conditions to check the platform then.

File: src/Ethereum/ABI/Array.cpp (hunk 6 above)
Comment (Milerius) [reply src/Ethereum/ABI/Array.cpp:149]: False parameter is for exception

**Review by miloserdow — COMMENTED** [review]
Cannot approve - not familiar with ETH ABI.

File: src/Ethereum/ABI/Array.h (hunk 4 above)
Comment (catenocrypt) [reply src/Ethereum/ABI/Array.h:67]: Padding should be applied, but that does not mean 32 has to be always added to the size!
I think correct would be 
```
[[nodiscard]] size_t getSize() const final { return ValueEncoder::paddedTo32(_params.getSize()); }
```

Comment (catenocrypt) [reply src/Ethereum/ABI/Array.h:67]: Actually this is not needed, ParamSet::getSize() always pads.
So simply:
```
[[nodiscard]] size_t getSize() const final { return _params.getSize(); }
```

File: src/Ethereum/ABI/Array.cpp (hunk 5 above)
Comment (catenocrypt) [reply src/Ethereum/ABI/Array.cpp:166]: In general, asserts should be used to test for internal inconsistencies, but not for invalid input data.

File: src/Ethereum/ABI/Array.cpp [hunk 7]
```diff
@@ -133,4 +133,44 @@ std::string ParamArray::getExtraTypes(std::vector<std::string>& ignoreList) cons
...
+void ParamArrayFix::encode(Data& data) const {
+    this->_params.encode(data);
+}
+
+bool ParamArrayFix::decode(const Data& encoded, size_t& offset_inout) {
+    std::size_t origOffset = offset_inout;
+    auto res = this->_params.decode(encoded, offset_inout);
+    // padding
+    offset_inout = origOffset + ValueEncoder::paddedTo32(offset_inout - origOffset);
+    return res;
```
Comment (catenocrypt) [inline src/Ethereum/ABI/Array.cpp:145]:
```suggestion
    return this->_params.decode(encoded, offset_inout);
```

Padding here does not hurt, but in fact it is not needed. If it is done here, it should check for size, otherwise it could happen that offset runs out of input data. Better to leave it out completely. It is also difficult to test.

File: src/Ethereum/ABI/Array.cpp [hunk 8]
```diff
@@ -133,4 +133,44 @@ std::string ParamArray::getExtraTypes(std::vector<std::string>& ignoreList) cons
...
+}
+
+bool ParamArrayFix::setValueJson(const std::string& value) {
+    auto valuesJson = json::parse(value, nullptr, false);
+    if (valuesJson.is_discarded() || !valuesJson.is_array() || _params.getCount() < valuesJson.size()) {
```
Comment (catenocrypt) [inline src/Ethereum/ABI/Array.cpp:150]: Size comparison is not strict here, and in fact reversed. If more elements are provided, that is rejected, while if less, that's accepted.
I suggest making the condition strict, change `<` into `!=`.

File: tests/Ethereum/AbiStructTests.cpp [hunk 9]
```diff
@@ -892,6 +892,23 @@ TEST(EthereumAbiStruct, ParamHashStruct) {
...
+    {
+        using collection = std::vector<std::shared_ptr<ParamBase>>;
+        auto p = std::make_shared<ParamArrayFix>(collection{std::make_shared<ParamUInt8>(), std::make_shared<ParamUInt8>(), std::make_shared<ParamUInt8>()});
+        EXPECT_TRUE(p->setValueJson("[13,14,15]"));
+        EXPECT_EQ(hex(p->hashStruct()), "000000000000000000000000000000000000000000000000000000000000000d000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000f");
+
+        // Coverage
+        EXPECT_FALSE(p->setValueJson("NotValidJson"));
+        EXPECT_FALSE(p->setValueJson("{}"));
+        EXPECT_FALSE(p->setValueJson("[1,2,3,4]"));
```
Comment (catenocrypt) [inline tests/Ethereum/AbiStructTests.cpp:910]: Add also negative test with array with less elements.

**Review by catenocrypt — CHANGES_REQUESTED** [review]

File: src/Ethereum/ABI/Array.cpp (hunk 8 above)
Comment (Milerius) [reply src/Ethereum/ABI/Array.cpp]: Thanks, I had a doubt here if we should accept partial overriding!

File: tests/Ethereum/AbiStructTests.cpp (hunk 9 above)
Comment (Milerius) [reply tests/Ethereum/AbiStructTests.cpp:910]: Done

File: src/Ethereum/ABI/Array.cpp (hunk 7 above)
Comment (Milerius) [reply src/Ethereum/ABI/Array.cpp]: done

**Review by catenocrypt — APPROVED** [review]
