### PR TITLE
Fix Bitcoin Cash address validation

### LINKED ISSUE #143: Crash when sending to a certain BCH address
Sending to this BCH  address   `pqx578nanz2h2estzmkr53zqdg6qt8xyqvwhn6qeyc`

Crashes both Android and iOS app.

The user got it from a wallet called Coin.ph Wallet

### PR DESCRIPTION
**Pull request by alejandro-isaza**
Fix #143

### CODE REVIEW

File: src/interface/TWBitcoinCashAddress.cpp [hunk 1]
```diff
@@ -28,33 +29,19 @@ bool TWBitcoinCashAddressIsValid(TWData *_Nonnull data) {
...
 }
 
 bool TWBitcoinCashAddressInitWithString(struct TWBitcoinCashAddress *_Nonnull address, TWString *_Nonnull string) {
-    uint8_t data[104];
-    char hrpBuf[29];
-    size_t dataLen;
-    if (cash_decode(hrpBuf, data, &dataLen, TWStringUTF8Bytes(string)) == 0) {
+    auto& stdString = *reinterpret_cast<const std::string*>(string);
+    try {
+        const auto addr = TW::Bitcoin::CashAddress(stdString);
```
Comment (vikmeup) [inline src/interface/TWBitcoinCashAddress.cpp]: Add test on which address it was failing?

Comment (alejandro-isaza) [reply src/interface/TWBitcoinCashAddress.cpp]: done
