### PR TITLE
Ethereum ABI: Fix for handling empty arrays

### LINKED ISSUE #2207: Wrong eip-712 digest hash when empty array occurs in  json
**Describe the bug**
When occurs empty array in json, the `ParamStruct::hashStructJson` will not work well, for example:
```json
{
    "types": {
        "EIP712Domain": [
            {
                "name": "chainId",
                "type": "uint256"
            },
            {
                "name": "name",
                "type": "string"
            },
            {
                "name": "verifyingContract",
                "type": "address"
            },
            {
                "name": "version",
                "type": "string"
            }
        ],
        "Action": [
            {
                "name": "action",
                "type": "string"
            },
            {
                "name": "params",
                "type": "string"
            }
        ],
        "Cell": [
            {
                "name": "capacity",
                "type": "string"
            },
            {
                "name": "lock",
                "type": "string"
            },
            {
                "name": "type",
                "type": "string"
            },
            {
                "name": "data",
                "type": "string"
            },
            {
                "name": "extraData",
                "type": "string"
            }
        ],
        "Transaction": [
            {
                "name": "DAS_MESSAGE",
                "type": "string"
            },
            {
                "name": "inputsCapacity",
                "type": "string"
            },
            {
                "name": "outputsCapacity",
                "type": "string"
            },
            {
                "name": "fee",
                "type": "string"
            },
            {
                "name": "action",
                "type": "Action"
            },
            {
                "name": "inputs",
                "type": "Cell[]"
            },
            {
                "name": "outputs",
                "type": "Cell[]"
            },
            {
                "name": "digest",
                "type": "bytes32"
            }
        ]
    },
    "primaryType": "Transaction",
    "domain": {
        "chainId": 1,
        "name": "da.systems",
        "verifyingContract": "0x0000000000000000000000000000000020210722",
        "version": "1"
    },
    "message": {
        "DAS_MESSAGE": "TRANSFER FROM 0x54366bcd1e73baf55449377bd23123274803236e(906.74221046 CKB) TO ckt1qyqvsej8jggu4hmr45g4h8d9pfkpd0fayfksz44t9q(764.13228446 CKB), 0x54366bcd1e73baf55449377bd23123274803236e(142.609826 CKB)",
        "inputsCapacity": "906.74221046 CKB",
        "outputsCapacity": "906.74211046 CKB",
        "fee": "0.0001 CKB",
        "digest": "0x29cd28dbeb470adb17548563ceb4988953fec7b499e716c16381e5ae4b04021f",
        "action": {
            "action": "transfer",
            "params": "0x00"
        },
        "inputs": [],
        "outputs": []
    }
}
```
The `inputs` and `outputs` is set `[]`, and the outcome is wrong. (Different from MetaMask, which will result in a sig error)

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Fix handling of type of empty array: an array can be empty, but have a prototype element for its type.
Fixes #2207 .
See also #2205, by @pranksteess .

## Testing instructions

Unit tests, `*Ethereum*`.  New test file `eip712_emptyArray.json`.

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

File: src/Ethereum/ABI/Array.h [hunk 1]
```diff
@@ -13,10 +13,13 @@
 namespace TW::Ethereum::ABI {
 
 /// Dynamic array of the same types, "<type>[]"
+/// Normally has at least one element.  Empty array can have prototype set so its type is known.
+/// Empty with no prototype is possible, but should be avoided.
 class ParamArray: public ParamCollection
 {
 private:
     ParamSet _params;
+    std::shared_ptr<ParamBase> _proto; // an optional prototype element, determines the array type, useful in empty array case
```
Comment (pranksteess) [inline src/Ethereum/ABI/Array.h:22]: Cool~

**Review by hewigovens — APPROVED** [review]

**Comment by hewigovens** [comment]
@catenocrypt can you merge and tag a new version? going to release a new build for the app
