### PR TITLE
Fix 3 potential memory access errors (ASAN)

### LINKED ISSUE #1172: Possible memory access issues (ASAN)
Clang address sanitizer has found 3 potential memory access issues in unit tests (#1170 ).

```
./build/tests/tests tests --gtest_filter=*-Coin.DeriveAddress:HarmonyStaking.SignEditValidator:TWHarmonyStakingSigner*:*Nano*:*ClearMemory*:WalletConsole.addrDefault
```

Coin.DeriveAddress:
```
==41388==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee79260e2 at pc 0x00010a1608c6 bp 0x7ffee7926070 sp 0x7ffee7926068
WRITE of size 1 at 0x7ffee79260e2 thread T0
    #0 0x10a1608c5 in TW::Nano::Address::string() const (tests:x86_64+0x101e8b8c5)
```

NanoAddress.FromPublicKey:
```
==41417==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee3e7af42 at pc 0x00010dc0e8c6 bp 0x7ffee3e7aed0 sp 0x7ffee3e7aec8
WRITE of size 1 at 0x7ffee3e7af42 thread T0
    #0 0x10dc0e8c5 in TW::Nano::Address::string() const (tests:x86_64+0x101e8b8c5)
```

WalletConsole.addrDefault:
```
==41437==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffeefad2d02 at pc 0x000101fb58c6 bp 0x7ffeefad2c90 sp 0x7ffeefad2c88
WRITE of size 1 at 0x7ffeefad2d02 thread T0
    #0 0x101fb58c5 in TW::Nano::Address::string() const (tests:x86_64+0x101e8b8c5)
```

HarmonyStaking.SignEditValidator:
```
==41405==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffee5ae0170 at pc 0x00010a149030 bp 0x7ffee5adee00 sp 0x7ffee5adedf8
READ of size 8 at 0x7ffee5ae0170 thread T0
    #0 0x10a14902f in boost::multiprecision::backends::cpp_int_base<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void, false>::size() const cpp_int.hpp:820
    ...
    #5 0x10bc03374 in TW::Ethereum::RLP::encode(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0> const&) RLP.cpp:26
    #6 0x10bda4cde in TW::Harmony::Signer::rlpNoHashDirective(TW::Harmony::Staking<TW::Harmony::EditValidator> const&) const (tests:x86_64+0x101c88cde)
```

PrivateKey.ClearMemory:
```
==41430==ERROR: AddressSanitizer: heap-use-after-free on address 0x60300002bed0 at pc 0x000108759ba3 bp 0x7ffeeee89d60 sp 0x7ffeeee89528
READ of size 32 at 0x60300002bed0 thread T0
    #0 0x108759ba2 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x43ba2)
    ...
onst*>::type) vector:1209
    #5 0x100fda54a in TW::data(unsigned char const*, unsigned long) Data.h:28
    #6 0x101df1ba2 in PrivateKey_ClearMemory_Test::TestBody() PrivateKeyTests.cpp:144
```

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Fixes #1172 .

## Testing instructions

Unit tests, plus ASAN -- which is not yet committed, PR #1171 .

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

**Review by vikmeup — APPROVED** [review]
Is it possible to add this check into CI somehow?

**Comment by vikmeup** [comment]
from iOS CI:
```
❌  /Users/runner/work/wallet-core/wallet-core/swift/wallet-core/Harmony/Signer.cpp:444:76: 'value' is unavailable: introduced in iOS 12.0

        append(decEncoded, RLP::encode(transaction.stakeMsg.commissionRate.value().value));
```

Did you guys try to update CI to Xcode 12?

File: tests/interface/TWPrivateKeyTests.cpp [hunk 1]
```diff
@@ -85,24 +85,6 @@ TEST(TWPrivateKeyTests, PublicKey) {
...
 
-TEST(TWPrivateKeyTests, ClearMemory) {
-    auto privKey = "afeefca74d9a325cf1d6b6911d61a65c32afa8e02bd5e78e2e4ac2910bab45f5";
-    auto privKeyData = TW::parse_hex(privKey);
-    auto data = WRAPD(TWDataCreateWithBytes(privKeyData.data(), privKeyData.size()));
-    auto privateKey = TWPrivateKeyCreateWithData(data.get());
-    auto ptr = privateKey->impl.bytes.data();
-    ASSERT_EQ(privKey, TW::hex(TW::data(ptr, 32)));
-
-    TWPrivateKeyDelete(privateKey);
```
Comment (hewigovens) [inline tests/interface/TWPrivateKeyTests.cpp:96]: can we keep this test? inside `TWPrivateKeyDelete` is still `delete pk`, make sure it's cleared from C interface call

File: src/Harmony/Signer.cpp [hunk 2]
```diff
@@ -441,8 +440,9 @@ Data Signer::rlpNoHashDirective(const Staking<EditValidator> &transaction) const
     append(encoded, RLP::encodeList(descriptionEncoded));
 
     auto decEncoded = Data();
-    if (transaction.stakeMsg.commissionRate != nullptr) {
-        append(decEncoded, RLP::encode(transaction.stakeMsg.commissionRate->value));
+    if (transaction.stakeMsg.commissionRate.has_value()) {
+        // Note: std::optional.value() is not available in XCode with target < iOS 12; using '*'
```
Comment (hewigovens) [inline src/Harmony/Signer.cpp:444]: probably time to only support iOS 12 +

Comment (catenocrypt) [reply src/Harmony/Signer.cpp:444]: For this particular issue it's not a big deal, instead of optional.value() alternative is *optional.

File: tests/interface/TWPrivateKeyTests.cpp (hunk 1 above)
Comment (catenocrypt) [reply tests/interface/TWPrivateKeyTests.cpp:96]: This test was tricky, I struggled with it already.  It tests the content of the memory after being freed, which is not valid.  The test result was sporadic, as that memory is often reused quickly (hence the probabilistic check, not compare to all 0s).  The sanitizer caught the invalid memory access done by the test.
'Zero memory before deallocation' is a security feature, but impossible to test properly.

**Comment by catenocrypt** [comment]
> Did you guys try to update CI to Xcode 12?

I think 12 here refers to the min target iOS platform version, not Xcode version.  BTW this error is not a big deal, '*optional' is a good alternative for 'optional.value()'.

File: src/Harmony/Signer.cpp (hunk 2 above)
Comment (hewigovens) [reply src/Harmony/Signer.cpp:444]: our app supports iOS 13+, now iOS 14 comes out, iOS 12/13/14 should be good enough, besides we had at least 3 times build failure because of `optional.value()`

**Review by hewigovens — APPROVED** [review]
