### PR TITLE
Fix unsafe pointer return to object return

### LINKED ISSUE #1164: StoredKey::account() returns unsafe pointer
StoredKey::account() returns a pointer to an account instance, that can change after being returned.
It returns a pointer to one element in its accounts vector, but the address of elements may change, e.g. if new elements are added.
The contents of a returned pointer may change later, resulting in unpredicted behaviour.  It is unsafe, as returned pointer may point to a different memory location.

Can be reproduces with following unit test (not that this is not fully deterministic, does not always change).

```
TEST(StoredKey, AccountGetDoesntChange) {
    auto key = StoredKey::createWithMnemonic("name", password, mnemonic);
    auto wallet = key.wallet(password);
    EXPECT_EQ(key.accounts.size(), 0);

    vector<TWCoinType> coins = {coinTypeBc, coinTypeEth, coinTypeBnb};
    // retrieve multiple accounts, which will be created
    vector<const Account*> accounts;
    for (auto coin: coins) {
        const Account* account = key.account(coin, &wallet);
        accounts.push_back(account);

        // check
        ASSERT_TRUE(account != nullptr);
        EXPECT_EQ(account->coin, coin);
    }

    // Check again; make sure returned references don't change
    for (auto i = 0; i < accounts.size(); ++i) {
        // check
        ASSERT_TRUE(accounts[i] != nullptr);
        EXPECT_EQ(accounts[i]->coin, coins[i]);
    }
}
```

Sample failure:
```
[ RUN      ] StoredKey.AccountGetDoesntChange
/Users/adam/tw/wallet-core/tests/Keystore/StoredKeyTests.cpp:162: Failure
Expected equality of these values:
  accounts[i]->coin
    Which is: 420224285
  coins[i]
    Which is: 0
/Users/adam/tw/wallet-core/tests/Keystore/StoredKeyTests.cpp:162: Failure
Expected equality of these values:
  accounts[i]->coin
    Which is: 1951608677
  coins[i]
    Which is: 60
[  FAILED  ] StoredKey.AccountGetDoesntChange (370 ms)
```

### PR DESCRIPTION
**Pull request by catenocrypt**
## Description

Instead of a pointer return (which may become unsafe), the object is returned (with optional, as null return is a valid case).
Only 2 internal classes affected, the C inerface and swift/kotlin not.
Fixes #1164 .

## Testing instructions

Standard unit tests; new unit test  `StoredKey.AccountGetDoesntChange`

## Types of changes

* Bug fix (non-breaking change which fixes an issue) 

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

### CODE REVIEW

File: src/interface/TWStoredKey.cpp [hunk 1]
```diff
@@ -97,7 +97,8 @@ struct TWAccount* _Nullable TWStoredKeyAccount(struct TWStoredKey* _Nonnull key,
 struct TWAccount* _Nullable TWStoredKeyAccountForCoin(struct TWStoredKey* _Nonnull key, enum TWCoinType coin, struct TWHDWallet* _Nullable wallet) {
     try {
         const auto account = key->impl.account(coin, (wallet ? &wallet->impl : nullptr));
-        return (account == nullptr) ? nullptr : new TWAccount{ *account };
+        // Note: std::optional.value() si not available in XCode with target < iOS 12, using *
```
Comment (hewigovens) [inline src/interface/TWStoredKey.cpp:100]:
```suggestion
```

**Review by hewigovens — APPROVED** [review]

**Review by leoneparise — APPROVED** [review]
