### PR TITLE
[Fix]: PVS-studio high warnings

### LINKED ISSUE #2371: [Analysis]: PVS-Studio warnings
**Describe the bug**

PVS-studio analysis has shown a few important warnings (see attached files)

```JSON
{
  "version": 2,
  "warnings": [
    {
      "code": "V808",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "'bytes' object of 'vector' type was created but was not utilized.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 66,
          "file": "|?|/src/Base64.cpp",
          "line": 66,
          "navigation": {
            "columns": 0,
            "currentLine": 49785,
            "nextLine": 737,
            "previousLine": 1340394732
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V823",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Object may be created in-place in the 'utxos' container. Consider replacing methods: 'push_back' -> 'emplace_back'.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 25,
          "file": "|?|/src/Bitcoin/SigningInput.cpp",
          "line": 25,
          "navigation": {
            "columns": 0,
            "currentLine": 1540494597,
            "nextLine": 125,
            "previousLine": 1286438333
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V591",
      "cwe": 393,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Non-void function should return a value.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 76,
          "file": "|?|/src/Result.h",
          "line": 76,
          "navigation": {
            "columns": 0,
            "currentLine": 125,
            "nextLine": 0,
            "previousLine": 125
          }
        }
      ],
      "projects": [],
      "sastId": "CERT-MSC52-CPP"
    },
    {
      "code": "V614",
      "cwe": 457,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Uninitialized variable 'success_' used.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 79,
          "file": "|?|/src/Result.h",
          "line": 79,
          "navigation": {
            "columns": 0,
            "currentLine": 373533,
            "nextLine": 1913548495,
            "previousLine": 251249673
          }
        }
      ],
      "projects": [],
      "sastId": "CERT-EXP53-CPP"
    },
    {
      "code": "V591",
      "cwe": 393,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Non-void function should return a value.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 99,
          "file": "|?|/src/Result.h",
          "line": 99,
          "navigation": {
            "columns": 0,
            "currentLine": 125,
            "nextLine": 0,
            "previousLine": 125
          }
        }
      ],
      "projects": [],
      "sastId": "CERT-MSC52-CPP"
    },
    {
      "code": "V823",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Object may be created in-place in the 'tx.outputs' container. Consider replacing methods: 'push_back' -> 'emplace_back'.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 51,
          "file": "|?|/src/Bitcoin/TransactionBuilder.h",
          "line": 51,
          "navigation": {
            "columns": 0,
            "currentLine": 1321756508,
            "nextLine": 125,
            "previousLine": 1233355944
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V823",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Object may be created in-place in the 'elems' container. Consider replacing methods: 'push_back' -> 'emplace_back'.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 317,
          "file": "|?|/src/Cbor.cpp",
          "line": 317,
          "navigation": {
            "columns": 0,
            "currentLine": -1920787482,
            "nextLine": 269283,
            "previousLine": 125
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V783",
      "cwe": 119,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Dereferencing of the invalid iterator 'outputsToSign.end()' might take place.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 55,
          "file": "|?|/src/Decred/Transaction.cpp",
          "line": 55,
          "navigation": {
            "columns": 0,
            "currentLine": -2143041588,
            "nextLine": 2337,
            "previousLine": 141055337
          }
        }
      ],
      "projects": [],
      "sastId": "CERT-CTR51-CPP"
    },
    {
      "code": "V832",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "It's better to use '= default;' syntax instead of empty constructor body.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 17,
          "file": "|?|/src/EOS/Name.h",
          "line": 17,
          "navigation": {
            "columns": 0,
            "currentLine": 13791,
            "nextLine": -1491989968,
            "previousLine": 0
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V823",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Object may be created in-place in the 'item.decoded' container. Consider replacing methods: 'push_back' -> 'emplace_back'.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 117,
          "file": "|?|/src/Ethereum/RLP.cpp",
          "line": 117,
          "navigation": {
            "columns": 0,
            "currentLine": -1324728997,
            "nextLine": -863523314,
            "previousLine": 983062771
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V629",
      "cwe": 190,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Consider inspecting the 'bytes[i] << shift' expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 155,
          "file": "|?|/src/Filecoin/Address.cpp",
          "line": 155,
          "navigation": {
            "columns": 0,
            "currentLine": 37286115,
            "nextLine": 2337,
            "previousLine": 11729449
          }
        }
      ],
      "projects": [],
      "sastId": "CERT-INT00-C"
    },
    {
      "code": "V828",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Moving a local object in a return statement prevents copy elision.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 30,
          "file": "|?|/src/NEO/ReadData.h",
          "line": 30,
          "navigation": {
            "columns": 0,
            "currentLine": 22588193,
            "nextLine": 125,
            "previousLine": 554609720
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V1043",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "A global object variable 'SS58Prefix' is declared in the header. Multiple copies of it will be created in all translation units that include this header file.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 15,
          "file": "|?|/src/Polkadot/SS58Address.h",
          "line": 15,
          "navigation": {
            "columns": 0,
            "currentLine": 43324018,
            "nextLine": 0,
            "previousLine": 0
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V823",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Object may be created in-place in the 'accountMetas' container. Consider replacing methods: 'push_back' -> 'emplace_back'.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 289,
          "file": "|?|/src/Solana/Transaction.h",
          "line": 289,
          "navigation": {
            "columns": 0,
            "currentLine": -1272229209,
            "nextLine": 125,
            "previousLine": -1663613836
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V827",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Maximum size of the 'instructions' vector is known at compile time. Consider pre-allocating it by calling instructions.reserve(3)",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 319,
          "file": "|?|/src/Solana/Transaction.h",
          "line": 319,
          "navigation": {
            "columns": 0,
            "currentLine": -1041605848,
            "nextLine": -707283705,
            "previousLine": -489151543
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V827",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Maximum size of the 'instructions' vector is known at compile time. Consider pre-allocating it by calling instructions.reserve(3)",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 454,
          "file": "|?|/src/Solana/Transaction.h",
          "line": 454,
          "navigation": {
            "columns": 0,
            "currentLine": -1041605848,
            "nextLine": 613283574,
            "previousLine": 2087801801
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V654",
      "cwe": 834,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "The condition 'seed >= 0' of loop is always true.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 67,
          "file": "|?|/src/Solana/Program.cpp",
          "line": 67,
          "navigation": {
            "columns": 0,
            "currentLine": 1118726667,
            "nextLine": 1500721312,
            "previousLine": -455637124
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V823",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Object may be created in-place in the 'ret' container. Consider replacing methods: 'push_back' -> 'emplace_back'.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 36,
          "file": "|?|/src/Solana/Signer.cpp",
          "line": 36,
          "navigation": {
            "columns": 0,
            "currentLine": 170017060,
            "nextLine": 125,
            "previousLine": 748439605
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V808",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "'stakePubkey' object of 'basic_string' type was created but was not utilized.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 46,
          "file": "|?|/src/Solana/Signer.cpp",
          "line": 46,
          "navigation": {
            "columns": 0,
            "currentLine": 360725765,
            "nextLine": -1171398899,
            "previousLine": 1721333
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V823",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "Decreased performance. Object may be created in-place in the 'pubs' container. Consider replacing methods: 'push_back' -> 'emplace_back'.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 32,
          "file": "|?|/src/TransactionCompiler.cpp",
          "line": 32,
          "navigation": {
            "columns": 0,
            "currentLine": 2096669909,
            "nextLine": 125,
            "previousLine": 125
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V808",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "'h' object of 'basic_string' type was created but was not utilized.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 43,
          "file": "|?|/src/Waves/Address.cpp",
          "line": 43,
          "navigation": {
            "columns": 0,
            "currentLine": 71602141,
            "nextLine": 1081734597,
            "previousLine": -100289524
          }
        }
      ],
      "projects": [],
      "sastId": ""
    },
    {
      "code": "V808",
      "cwe": 0,
      "falseAlarm": false,
      "favorite": false,
      "level": 1,
      "message": "'h2' object of 'basic_string' type was created but was not utilized.",
      "positions": [
        {
          "column": 1,
          "endColumn": 2147483647,
          "endLine": 44,
          "file": "|?|/src/Waves/Address.cpp",
          "line": 44,
          "navigation": {
            "columns": 0,
            "currentLine": 1081734597,
            "nextLine": -380811025,
            "previousLine": 71602141
          }
        }
      ],
      "projects": [],
      "sastId": ""
    }
  ]
}
```

**To Reproduce**

run pvs-studio analyzer

**Expected behavior**

No High warning

### PR DESCRIPTION
**Pull request by Milerius**
## Description

Fix all 22 high warnings from pvs-studio described in #2371 
fix #2371 

## How to test

run c++ unit tests

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

### CODE REVIEW

**Review by hewigovens — APPROVED** [review]
can you setup cmake or add a script to scan locally later?

**Comment by Milerius** [comment]
> can you setup cmake or add a script to scan locally later?

Yes during the cmake modernize pr :-)

File: src/Solana/Program.cpp [hunk 1]
```diff
@@ -64,20 +65,17 @@ Address TokenProgram::defaultTokenAddress(const Address& mainAddress, const Addr
...
     Address result(Data(32));
     // cycle through seeds for the rare case when result is not valid
-    for (uint8_t seed = 255; seed >= 0; --seed) {
-        std::vector<Data> seedsCopy;
-        for (auto& s: seeds) {
-            seedsCopy.push_back(s);
-        }
-        // add extra seed
-        seedsCopy.push_back({seed});
+    auto bumpSeed = Data{std::numeric_limits<std::uint8_t>::max()};
```
Comment (miloserdow) [inline src/Solana/Program.cpp:68]: I don't understand why it's the same logic after your change. Can you please explain?

Comment (Milerius) [reply src/Solana/Program.cpp:68]: > I don't understand why it's the same logic after your change. Can you please explain?

It just mimicate <https://github.com/solana-labs/solana/blob/b7e7e4159c10cc249cdfc27d54b72218eebcea65/sdk/program/src/pubkey.rs#L474> It's semantically wrong to write `unsigned value <= 0` because this is not possible, even if the new code reach the limit of `UCHAR_MAX` the semantic is correct.

**Review by miloserdow — APPROVED** [review]
